name: Test OrbitalML Examples

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  orbitalml-examples:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Build orbital package locally
        run: |
          python -m pip install --upgrade pip build
          python -m build
          
      - name: Build orbitalml package
        run: |
          cd proxypackage
          python -m build
          
      - name: Install packages with local dependencies
        run: |
          # Install orbital from local wheel with test dependencies
          pip install "dist/*.whl[test]"
          # Install orbitalml from local wheel (which depends on orbital)
          pip install proxypackage/dist/*.whl
      
      - name: Copy and modify examples
        run: |
          # Create test examples directory
          mkdir -p test_orbitalml_examples
          
          # Copy all Python examples from the examples directory
          cp examples/*.py test_orbitalml_examples/
          
          # Replace all "import orbital" with "import orbitalml as orbital"
          find test_orbitalml_examples -name "*.py" -exec sed -i 's/^import orbital$/import orbitalml as orbital/g' {} \;
          
          # Replace all "from orbital" with "from orbitalml"
          find test_orbitalml_examples -name "*.py" -exec sed -i 's/^from orbital/from orbitalml/g' {} \;
          
          # Replace "import orbital.types" and similar with commented orbital.types usage
          find test_orbitalml_examples -name "*.py" -exec sed -i 's/^import orbital\./# orbital.types available via: import orbitalml as orbital/g' {} \;

      - name: Run OrbitalML Examples
        run: |
          echo "Testing OrbitalML examples..."
          for example in test_orbitalml_examples/*.py; do
              if [[ -f "$example" ]]; then
                  echo "Running $example..."
                  python "$example"
                  echo "✓ $example completed successfully"
                  echo "---"
              fi
          done
          echo "All OrbitalML examples completed successfully!"
          
      - name: Verify no direct 'orbital' imports remain
        run: |
          echo "Checking for any remaining direct 'orbital' imports..."
          
          # Check for direct "import orbital" (not "import orbitalml")
          if grep -r "import orbital[^m]" test_orbitalml_examples/ || grep -r "import orbital$" test_orbitalml_examples/; then
            echo "❌ Found direct 'import orbital' - should be 'import orbitalml as orbital'"
            exit 1
          fi
          
          # Check for "from orbital" imports (should be "from orbitalml")
          if grep -r "from orbital " test_orbitalml_examples/; then
            echo "❌ Found 'from orbital' - should be 'from orbitalml'"
            exit 1
          fi
          
          # Verify we have the correct orbitalml imports
          if ! grep -r "import orbitalml as orbital" test_orbitalml_examples/ >/dev/null; then
            echo "❌ No 'import orbitalml as orbital' found in examples"
            exit 1
          fi
          
          echo "✓ All examples use 'orbitalml' correctly!"
